python -m sl_data_processing.encode_data --time 2017_black_0_won
python -m sl_data_processing.encode_data --time 2017_white_1_won
python -m sl_data_processing.encode_data --time 2018_black_0_won
python -m sl_data_processing.encode_data --time 2018_white_1_won
python -m sl_data_processing.encode_data --time 2019_black_0_won
python -m sl_data_processing.encode_data --time 2019_white_1_won
python -m sl_data_processing.encode_data --time 2020_1_black_0_won
python -m sl_data_processing.encode_data --time 2020_1_white_1_won
python -m sl_data_processing.encode_data --time 2020_2_black_0_won
python -m sl_data_processing.encode_data --time 2020_2_white_1_won
